/* fttDataWindowsB.idl
*
* Table: fttDataWindowsB
*
* description: sTGC (ftt) data time windows
*
*/

struct fttDataWindowsB {
	short uuid[385]; /* index = StFttDb::vmmId(hit) [0-383] */
	octet mode[385]; /* 0 = timebin, 1 = bcid */
	short min[385]; /* time window min > -32768 */
	short max[385]; /* time window max < 32768 */
	short anchor[385]; /* calibrated time anchor for BCID */
};
